"""
report_numbers.py
-----------------
One source of truth for every number quoted in the deck and the paper.

The experiment files under experiments/ (and the real-city validation JSON
under backend/experiments/phase7_validation/) are the evidence. This script
derives every headline figure from them in one place, writes it to
docs/generated/report_numbers.{json,md}, and can CHECK a PowerPoint deck or a
Word paper against those figures so a stale or hand-typed number is caught.

    python scripts/report_numbers.py                      # regenerate docs/generated/
    python scripts/report_numbers.py --check-deck deck.pptx
    python scripts/report_numbers.py --check-paper paper.docx

Checks exit non-zero when an expected figure is missing from the document.
Runtimes are machine-dependent, so they are reported but never checked;
costs, travel times and distances are deterministic and are.
"""
import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
EXPERIMENTS = ROOT / "experiments"
VALIDATION = ROOT / "backend" / "experiments" / "phase7_validation" / "validation_results.json"
OUT_DIR = ROOT / "docs" / "generated"

# The four algorithms the deck's benchmark table shows, in table order.
DECK_ALGOS = [
    ("greedy", "Greedy (Nearest Neighbour)"),
    ("pso", "Classical PSO"),
    ("ga", "Genetic Algorithm (GA)"),
    ("qpso_ls", "Q-DFRO (QPSO + local search)"),
]
HEADLINE_KEY = "qpso_ls"


def _pct_below(reference: float, value: float) -> float:
    """How much lower `value` is than `reference`, in percent."""
    return (reference - value) / reference * 100.0


def _read_csv(path: Path) -> List[dict]:
    with path.open(newline="", encoding="utf8") as f:
        return list(csv.DictReader(f))


def load_e1() -> Dict[str, dict]:
    rows = _read_csv(EXPERIMENTS / "E1_algorithm_comparison" / "results.csv")
    return {
        r["algorithm_key"]: {
            "algorithm": r["algorithm"],
            "total_cost": float(r["total_cost"]),
            "total_travel_time": float(r["total_travel_time"]),
            "total_distance": float(r["total_distance"]),
            "runtime_ms": float(r["runtime_ms"]),
            "is_feasible": r["is_feasible"] == "True",
        }
        for r in rows
    }


def real_city_summary() -> dict:
    """Per real city: how far QPSO is below Greedy, and how far it is from the
    best of the four algorithms. Ranges are taken over the cities."""
    data = json.loads(VALIDATION.read_text(encoding="utf8"))
    cities = []
    for loc in data["locations"]:
        bench = loc.get("benchmark")
        if not bench:
            continue
        costs = {k: v["total_cost"] for k, v in bench.items()}
        best_key = min(costs, key=costs.get)
        cities.append({
            "place": loc["place"],
            "best_algorithm": best_key,
            "qpso_below_greedy_pct": round(_pct_below(costs["greedy"], costs["qpso"]), 2),
            "qpso_above_best_pct": round((costs["qpso"] - costs[best_key]) / costs[best_key] * 100.0, 2),
        })
    below = [c["qpso_below_greedy_pct"] for c in cities]
    above = [c["qpso_above_best_pct"] for c in cities]
    return {
        "cities": cities,
        "qpso_below_greedy_pct_range": [min(below), max(below)] if below else None,
        "qpso_above_best_pct_range": [min(above), max(above)] if above else None,
    }


def build_numbers() -> dict:
    e1 = load_e1()
    q, greedy, pso, ga = e1[HEADLINE_KEY], e1["greedy"], e1["pso"], e1["ga"]
    numbers = {
        "e1": e1,
        "e1_headline": {
            "km_fewer_vs_greedy_pct": round(_pct_below(greedy["total_distance"], q["total_distance"]), 1),
            "cost_below_greedy_pct": round(_pct_below(greedy["total_cost"], q["total_cost"]), 1),
            "cost_below_pso_pct": round(_pct_below(pso["total_cost"], q["total_cost"]), 1),
            "cost_below_ga_pct": round(_pct_below(ga["total_cost"], q["total_cost"]), 1),
            "greedy_costs_more_pct": round((greedy["total_cost"] / q["total_cost"] - 1.0) * 100.0, 1),
        },
        "real_cities": real_city_summary(),
    }
    e7 = EXPERIMENTS / "E7_optimality_gap" / "summary.json"
    if e7.exists():
        numbers["e7"] = json.loads(e7.read_text(encoding="utf8"))
    e8 = EXPERIMENTS / "E8_warm_start" / "summary.json"
    if e8.exists():
        numbers["e8"] = json.loads(e8.read_text(encoding="utf8"))
    return numbers


def render_markdown(n: dict) -> str:
    h = n["e1_headline"]
    lines = [
        "# Report numbers (generated)",
        "",
        "Generated by `scripts/report_numbers.py` from the files under `experiments/` and",
        "`backend/experiments/phase7_validation/`. Do not edit by hand; regenerate instead.",
        "",
        "## E1 - algorithm comparison (30 nodes, 15 jobs, 3 vehicles, seed 42)",
        "",
        "| Algorithm | Cost | Travel time | Distance | Runtime (machine-dependent) |",
        "|---|---|---|---|---|",
    ]
    for key, r in n["e1"].items():
        lines.append(
            f"| {r['algorithm']} | {r['total_cost']:.2f} | {r['total_travel_time']:.2f} min | "
            f"{r['total_distance']:.2f} km | {r['runtime_ms']:.2f} ms |"
        )
    lines += [
        "",
        f"- QPSO + local search drives **{h['km_fewer_vs_greedy_pct']}%** fewer km than Greedy.",
        f"- Its cost is **{h['cost_below_greedy_pct']}%** below Greedy, **{h['cost_below_pso_pct']}%** below PSO, "
        f"**{h['cost_below_ga_pct']}%** below GA.",
        f"- Greedy costs **{h['greedy_costs_more_pct']}%** more than QPSO + local search.",
        "",
    ]
    rc = n["real_cities"]
    if rc["cities"]:
        lines += ["## Real cities (Phase 7 validation)", "",
                  "| City | Lowest-cost algorithm | QPSO below Greedy | QPSO above best |", "|---|---|---|---|"]
        for c in rc["cities"]:
            lines.append(f"| {c['place']} | {c['best_algorithm']} | {c['qpso_below_greedy_pct']}% | {c['qpso_above_best_pct']}% |")
        lines += ["",
                  f"- QPSO is {rc['qpso_below_greedy_pct_range'][0]}-{rc['qpso_below_greedy_pct_range'][1]}% below Greedy in every city.",
                  f"- QPSO is {rc['qpso_above_best_pct_range'][0]}-{rc['qpso_above_best_pct_range'][1]}% above the best algorithm per city.",
                  ""]
    if "e7" in n:
        lines += [f"## E7 - gap to the exact optimum ({n['e7']['instances']} instances)", "",
                  "| Algorithm | Mean gap | Max gap | Found the optimum |", "|---|---|---|---|"]
        for key, a in n["e7"]["algorithms"].items():
            if key == "exact" or a["mean_gap_pct"] is None:
                continue
            lines.append(f"| {key} | {a['mean_gap_pct']:.2f}% | {a['max_gap_pct']:.2f}% | {a['found_optimum']}/{a['runs']} |")
        lines.append("")
    if "e8" in n:
        f = n["e8"]["budgets"]["full"]
        lines += [f"## E8 - warm start ({n['e8']['incidents']} incidents, full budget)", "",
                  f"- Vehicles with a changed route: cold {f['cold']['mean_vehicles_changed']:.2f}, warm {f['warm']['mean_vehicles_changed']:.2f}",
                  f"- Mean cost: cold {f['cold']['mean_cost']:.2f}, warm {f['warm']['mean_cost']:.2f}",
                  f"- Warm cheaper / equal / dearer: {f['warm_cheaper']} / {f['warm_equal']} / {f['warm_dearer']}",
                  ""]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Expected strings and checking
# --------------------------------------------------------------------------

def expected_deck_strings(n: dict) -> List[Tuple[str, str]]:
    """(label, text that must appear) - formatted the way the deck prints them."""
    out = []
    for key, _ in DECK_ALGOS:
        r = n["e1"][key]
        out += [
            (f"{key} cost", f"{r['total_cost']:.2f}"),
            (f"{key} travel time", f"{r['total_travel_time']:.1f} min"),
            (f"{key} distance", f"{r['total_distance']:.1f} km"),
        ]
    h = n["e1_headline"]
    out += [
        ("km fewer vs Greedy", f"{h['km_fewer_vs_greedy_pct']}%"),
        ("cost below Greedy", f"{h['cost_below_greedy_pct']}%"),
        ("cost below GA", f"{h['cost_below_ga_pct']}%"),
        ("cost below PSO", f"{h['cost_below_pso_pct']}%"),
        ("Greedy costs more", f"{h['greedy_costs_more_pct']}%"),
    ]
    return out


def expected_paper_strings(n: dict) -> List[Tuple[str, str]]:
    """The paper's E1 table prints each metric to two decimals."""
    out = []
    for key, r in n["e1"].items():
        out += [
            (f"{key} cost", f"{r['total_cost']:.2f}"),
            (f"{key} travel time", f"{r['total_travel_time']:.2f}"),
            (f"{key} distance", f"{r['total_distance']:.2f}"),
        ]
    return out


def find_missing(text: str, expected: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
    return [(label, s) for label, s in expected if s not in text]


def extract_pptx_text(path: Path) -> str:
    from pptx import Presentation

    def walk(shapes):
        for sh in shapes:
            if sh.shape_type == 6:
                yield from walk(sh.shapes)
            else:
                yield sh

    parts = []
    for slide in Presentation(str(path)).slides:
        for sh in walk(slide.shapes):
            if sh.has_text_frame:
                parts.append(sh.text_frame.text)
            if getattr(sh, "has_table", False) and sh.has_table:
                parts += [c.text for row in sh.table.rows for c in row.cells]
        if slide.has_notes_slide:
            parts.append(slide.notes_slide.notes_text_frame.text)
    return "\n".join(parts)


def extract_docx_text(path: Path) -> str:
    import docx

    d = docx.Document(str(path))
    parts = [p.text for p in d.paragraphs]
    for t in d.tables:
        parts += [c.text for row in t.rows for c in row.cells]
    return "\n".join(parts)


def write_outputs(n: dict) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "report_numbers.json").write_text(json.dumps(n, indent=2), encoding="utf8")
    (OUT_DIR / "report_numbers.md").write_text(render_markdown(n), encoding="utf8")


def _report(kind: str, path: str, missing: List[Tuple[str, str]], total: int) -> int:
    if not missing:
        print(f"OK: {kind} '{path}' contains all {total} expected figures.")
        return 0
    print(f"DRIFT: {kind} '{path}' is missing {len(missing)} of {total} expected figures:")
    for label, s in missing:
        print(f"  - {label}: expected '{s}'")
    return 1


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check-deck", metavar="PPTX")
    parser.add_argument("--check-paper", metavar="DOCX")
    args = parser.parse_args(argv)

    numbers = build_numbers()
    if not (args.check_deck or args.check_paper):
        write_outputs(numbers)
        print(f"Wrote {OUT_DIR / 'report_numbers.json'} and report_numbers.md")
        return 0

    status = 0
    if args.check_deck:
        exp = expected_deck_strings(numbers)
        status |= _report("deck", args.check_deck, find_missing(extract_pptx_text(Path(args.check_deck)), exp), len(exp))
    if args.check_paper:
        exp = expected_paper_strings(numbers)
        status |= _report("paper", args.check_paper, find_missing(extract_docx_text(Path(args.check_paper)), exp), len(exp))
    return status


if __name__ == "__main__":
    sys.exit(main())
